---
- name: install mysql
  apt: 
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - mysql-server
    - mysql-client
    - python3-mysqldb

- name: change root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
  ignore_errors: yes
  # При первой прокатке пароль рута пустой
  # При второй вылетает ошибка доступа, игнорируем
...
