---
- name: my db play
  hosts: db
  gather_facts: yes
  become: yes

  tasks:
    - name: include role mysql
      include_role: 
        name: mysql
      vars:

  tasks:
    - name: include role php
      include_role:
        name: php
      vars:

...
