---
- name: my front play
  hosts: front
  gather_facts: yes
  become: yes

  tasks:
  - name: include role php
    include_role:
      name: php
    vars:

  - name: include role nginx
    include_role: 
      name: nginx
    vars:
...
