---
- name: install nginx
  apt:
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - nginx

- name: disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

...
