---
- name: my front play
  hosts: all
  gather_facts: yes
  become: yes

  # tasks:    
  #   - name: install nginx
  #     apt:
  #       name: nginx

    # - name: replace default nging config
    #   copy:
    #     dest: /etc/nginx/sites-enabled/default
    #     content: |
    #       server {
    #         listen 80;
    #         server_name _;

    #         location / {
    #           include uwsgi_params;
    #           uwsgi_pass uwsgi://{{ local_pytime_socket }};
    #         }
    #       }
    #   notify: restart nginx

  # любой notify отщелкивается только в конце play
  # handlers:
  #   - name: restart nginx
  #     systemd:
  #       name: nginx
  #       state: restarted
...
