---
- name: install mysql
  apt: 
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - mysql-server
    - mysql-client
    - python3-mysqldb

# TODO: нужно сменить пароль рута, если это первая прокатка
#       при второй проходит проверка доступа к mysql
- name: config mysql
  block:
    - name: checking access to mysql
      mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
  rescue:
    - name: change root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
      # При первой прокатке пароль рута пустой

...
